### ISSUE TITLE
show() method should return a Future

### ISSUE THREAD

**Issue by kylethompson-hs** [dbilgin/swipe_image_gallery#10]
The show() method of SwipeImageGallery should return a Future so that callers can await it and know when the gallery is closed.  The show() method is already an async function so the only that the needs to change is the return signature.

**Comment by dbilgin** [comment]
Hello @kylethompson-hs !
Thanks for opening an issue and nice catch with the return value.
I have just made a new release `0.8.3`. The problem should be fixed there, if you have any further issues do let me know.
