### ISSUE TITLE
Cannot dismiss using back button

### ISSUE THREAD

**Issue by minhdanh** [dbilgin/swipe_image_gallery#13]
I tried using the back button to dismiss the gallery but it doesn't work.
I also tried using an overlay and use `PopScope` but didn't work either.
How can we handle the back button on Android in this case?

**Comment by dbilgin** [comment]
Hi there @minhdanh, thanks for opening an issue.
This is an issue I cannot reproduce, you can also try with the example project within the package if you like to see if it works.
If you have a specific case where this doesn't work, I would need a code example reproducing this issue.

**Comment by minhdanh** [comment]
Hi @dbilgin Thanks for your reply. I tried to create a minimal code base that should reproduce the issue but it didn't have such problem. So it should be problem on my side. I'm closing this now.

**Comment by minhdanh** [comment]
Hi @dbilgin, sorry to bother you again haha. I just found out that I can fix this but need to introduce an option named `useRootNavigator`. I created a PR. The value of `useRootNavigator` is true by default so it should not cause a breaking change. Can you please check? 😅

**Comment by dbilgin** [comment]
No problem at all, just made the release [v0.8.6](https://github.com/dbilgin/swipe_image_gallery/releases/tag/v0.8.6), thanks for your contribution @minhdanh!
