### ISSUE TITLE
Please add click disappear function.

### ISSUE THREAD

**Issue by WangXiaoRi** [dbilgin/swipe_image_gallery#17]

**Comment by dbilgin** [comment]
Hi @WangXiaoRi, thanks for opening an issue, but I will need you to elaborate on what you mean and add some details.

**Comment by WangXiaoRi** [comment]
Now there is the function of dragging down and disappearing. I hope to add the function of disappearing with one tap.

**Comment by dbilgin** [comment]
Got it, this already exists with overlays, can you please check out the example project? There is also some instructions in the readme under "Add an Overlay".
Let me know if you need anything else.

**Comment by WangXiaoRi** [comment]
ok,thanks
