### ISSUE TITLE
Make opacity of overlay and opacity of background controllable

### ISSUE THREAD

**Issue by Windisch94** [dbilgin/swipe_image_gallery#18]
Hi,

is it possible to have a background opacity without touching the opacity of the overlay controller? this would be really nice

**Comment by dbilgin** [comment]
Hi @Windisch94, thanks for opening an issue, that's a very good catch!
I just made a new release with this, please check out [v0.8.8](https://github.com/dbilgin/swipe_image_gallery/releases/tag/v0.8.8). Let me know if it doesn't resolve your issue.
