### ISSUE TITLE
Swipe direction

### ISSUE THREAD

**Issue by devbrisk** [dbilgin/swipe_image_gallery#19]
Please add a direction option to swipe left or right.
Add a Directionality widget can do that.

**Comment by dbilgin** [comment]
Hi @devbrisk thanks for opening an issue, could you elaborate? Do you want the capability to go `4 3 2 1` rather than `1 2 3 4` when swiping left or right?

**Comment by devbrisk** [comment]
Yes exactly

**Comment by dbilgin** [comment]
Got it, will have a look at this, thanks!

**Comment by dbilgin** [comment]
Hi @devbrisk, sorry for getting back to you on this so late, I just made a new release [v0.8.9](https://github.com/dbilgin/swipe_image_gallery/releases/tag/v0.8.9). There is now support for a `reverseDirection` boolean property. You can simply pass it when initializing the package.

```dart
 await SwipeImageGallery(
   context: context,
   children: images,
   reverseDirection: true,
 ).show();
```
