### ISSUE TITLE
Strange hero animation issue when swiping to a different image and then dismissing

### ISSUE THREAD

**Issue by lampemw** [dbilgin/swipe_image_gallery#21]
Hi, I'm wondering if you can help with this issue. If I have hero tags enabled and swipe to a different image, when I swipe down to dismiss the current image, the initial image I tapped on in blank, and the hero animation appears to move the original image from the current image back into place while the large fullscreen image has a hero animation back into place as well. See the example in my video (cropped to remove some info). 

I open the first image, swipe to the 3rd image, and when swiping down to dismiss, the 1st image is blank until it appears to animate from the 3rd images location.

https://github.com/user-attachments/assets/481a5cc6-6e35-4001-9907-b95c7aa3d738

**Comment by dbilgin** [comment]
Hi @LampeMW, thank you for opening an issue, especially with a video example!
Unfortunately there doesn't seem to be a straightforward way to handle this, at least not as far as I know, but any contribution to work around this is welcome.

Although, I agree that the current look is terrible, therefore I created an example screen for you that shows how you can work around this issue as best as possible. Please see [multi_hero_animation_screen.dart](https://github.com/dbilgin/swipe_image_gallery/blob/master/example/lib/multi_hero_animation_screen.dart). You can also simply clone the repo and run the example project to see how it looks and feels.

Will be closing this issue for now, but you can let me know if there is anything else.
