### ISSUE TITLE
[feature request] ability to disable dismiss by vertically swiping

### ISSUE THREAD

**Issue by BLumia** [dbilgin/swipe_image_gallery#24]
Currently we have a `dismissDragDistance` argument to adjust the swiping distance to dismiss image gallery, but I prefer disable it and only offer a way that allow user dismiss image gallery via the overlay.

And I also have another feature request that adjust the gallery direction (PageView's `scrollDirection`) to vertical instead of horizontal. It's sort of related to this request since currently we hardcoded the swiping guesture as vertical swipe. Let me know if it's acceptable and/or if I need to create another issue for that request.

Thanks!

**Comment by dbilgin** [comment]
Hey @BLumia! That's a great request I believe, I have implemented both full-on vertical support and a way to disable drag-to-dismiss.
You can check out [v0.9.0](https://github.com/dbilgin/swipe_image_gallery/releases/tag/v0.9.0). You can let me know if you have any issues 🚀
