### ISSUE TITLE
Error: The method 'withValues' isn't defined for the class 'Color'.

### ISSUE THREAD

**Issue by mfurkanyuceal** [dbilgin/swipe_image_gallery#28]
I can't get a build on my app. Are you sure that increasing the patch number is the only way to achieve such a capability?
It isn't right to provide 3.27.0 support by increasing the patch number.

pubspec.yaml usage

swipe_image_gallery: ^0.9.0

Flutter version 3.24.5

![image](https://github.com/user-attachments/assets/765507ea-94ac-4514-93da-731713ed00e2)

**Comment by mfurkanyuceal** [comment]
I resolved my issue with changing swipe image gallery: 0.9.0 in pubspec yaml file. (^ removed)

**Comment by dbilgin** [comment]
You are definitely right on that, I just made a release [0.9.2](https://github.com/dbilgin/swipe_image_gallery/releases/tag/v0.9.2) reverting this change, will publish the flutter upgrade together with v0.10.0, you should be able to add `^` still.

Thanks for opening an issue, please let me know if you have more issues.
