### ISSUE TITLE
Add opportunity to change opacity of overlay

### ISSUE THREAD

**Issue by bonsoirelliot** [dbilgin/swipe_image_gallery#4]
Hello! Is there any way to animate the opacity of overlay while dragging the image down?

**Comment by dbilgin** [comment]
hi @bonsoirelliot thank you for opening an issue.
Do you mean changing the opacity of the overlay in sync with the rest of the content?

**Comment by bonsoirelliot** [comment]
I mean changing the opacity of the overlay in sync with the background of picture

**Comment by dbilgin** [comment]
@bonsoirelliot got it, it should be possible, I'll take a look at it and let you know, thanks

**Comment by dbilgin** [comment]
@bonsoirelliot this is fixed with the [v0.5.2](https://github.com/dbilgin/swipe_image_gallery/releases/tag/v0.5.2), let me know if there are any more problems with it. Thanks again for opening the issue
