### ISSUE TITLE
Swipe not working on Linux build

### ISSUE THREAD

**Issue by moovida** [dbilgin/swipe_image_gallery#6]
Hello, while developing I am used to use the linux version of my app. 

While the swipe image gallery works perfectly on android, I noticed that in linux it is malfunctioning.

Symptoms upon opening:

* the first image of the gallery opens as it should
* swipe does not work, the feeling is as if the gallery froze
* dragging from the very top (or bottom) in the opposite direction closes the gallery
* there is no way though, to see the other images

Do you experience the same issue.

Thanks for the nice library.

**Comment by dbilgin** [comment]
Hi @moovida !

Thank you for opening the issue, I will take a look at this and get back to you about it as soon as I can.

**Comment by dbilgin** [comment]
Hi @moovida,

Thanks again for reporting the issue. I have made a new release [0.8.0](https://github.com/dbilgin/swipe_image_gallery/releases/tag/v0.8.0). Please check it out. Now it has trackpad, touch and mouse support, you can also swipe using the keyboard arrow keys. You should be able to swipe on all platforms as expected.

Let me know if you experience any more problems. Have a nice day! :)

**Comment by moovida** [comment]
Hi @dbilgin , just tested with 0.8.0 and it just works like a charm! Thank you so much!
