### ISSUE TITLE
index of gallery

### ISSUE THREAD

**Issue by MichalNemec** [dbilgin/swipe_image_gallery#7]
Hello, how can i set index to open up gallery at specific image when the specific image is clicked? thanks!

**Comment by MichalNemec** [comment]
remove controller and initial is working

**Comment by dbilgin** [comment]
Hi @MichalNemec I see you have found a solution, but you should also be able to achieve this using the controller as `ImageGalleryController galleryController = ImageGalleryController(initialPage: 2);`

**Comment by MichalNemec** [comment]
hello, i need it reactive and i dont know if setting a controller like that is good option.
i need setstate to dynamically change the index for pageview and for this image gallery.

Awesome library tho! i hope the leaving jitter is only on android emulator, otherwise i appreaciate what you did!

**Comment by dbilgin** [comment]
@MichalNemec thank you very much :)
If you could give me an exact example of what you mean by "reactive", I may be able to help you with that. Maybe you just need to set `galleryController = ImageGalleryController(initialPage: dynamicValue);` every time?
Also not sure about the jitter on Android, can you maybe provide an example for that if it persists on a separate issue?
