### ISSUE TITLE
rror G9EFD8EEC: Member not found: 'trackpad'.

### ISSUE THREAD

**Issue by untillnesss** [dbilgin/swipe_image_gallery#8]
I tried to use the library you created on the Windows platform, and when I ran my program, I found an error like the following.

![image](https://user-images.githubusercontent.com/33585758/213890475-f5fce762-9ad7-42b9-b706-27bd20c3d96d.png)

And I'm more focused on the error `error G9EFD8EEC: Member not found: 'trackpad'.`
It should be compatible with the Windows platform.

**Comment by dbilgin** [comment]
hey @untillnesss, thank you for reporting this issue, going to check it out and get back to you on it

**Comment by dbilgin** [comment]
This issue is fixed with the 0.8.1 release. Please reach out if you experience it further.
