### ISSUE TITLE
Transparent backgroundColor displayed as solid color

### ISSUE THREAD

**Issue by g-30** [dbilgin/swipe_image_gallery#9]
I tried setting a semi-transparent color to `backgroundColor` property of SwipeImageGallery widget and the color was solid instead. Transparency option seems to be ignored. Please advise

**Comment by dbilgin** [comment]
hi @g-30 thank you for opening an issue!
I was just able to get around to this, I added a `backgroundOpacity` property to v0.8.2, please try using that and let me know if you have any further problems.
